# PHASE 1

In [1]:
!pip install beautifulsoup4 requests

import requests
from bs4 import BeautifulSoup
import csv

# Send a GET request to the IMDb URL
url = "https://www.imdb.com/search/title/?genres=action&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=f11158cc-b50b-4c4d-b0a2-40b32863395b&pf_rd_r=XZ8X52H1R40B7KG5SNZ9&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_1"
response = requests.get(url)

# Create BeautifulSoup object to parse the HTML content
soup = BeautifulSoup(response.content, 'html.parser')

# Extract movie details from the parsed HTML
movies = soup.find_all('div', class_='lister-item mode-advanced')

# Define the CSV file names
first_csv_file = 'movies_data.csv'

# Define the field names for the first CSV file
fieldnames = ['Sno', 'Movie Name', 'Director1', 'Director2', 'Duration', 'Year', 'Ratings', 'Metascore']

# Create and open the first CSV file in write mode
with open(first_csv_file, 'w', newline='', encoding='utf-8') as file:
    writer = csv.DictWriter(file, fieldnames=fieldnames)

    # Write the header row
    writer.writeheader()

    # Iterate over each movie
    for i, movie in enumerate(movies, start=1):
        # Extract movie details
        title = movie.h3.a.text
        directors = movie.find_all('p')[2].find_all('a')
        director1 = directors[0].text if len(directors) > 0 else ""
        director2 = directors[1].text if len(directors) > 1 else ""
        duration = movie.find('span', class_='runtime').text.strip(' min')
        year = movie.find('span', class_='lister-item-year').text.strip('()')
        ratings = movie.find('div', class_='inline-block ratings-imdb-rating').strong.text
        metascore = movie.find('span', class_='metascore').text.strip() if movie.find('span', class_='metascore') else ""

        # Write movie data to the CSV file
        writer.writerow({
            'Sno': i,
            'Movie Name': title,
            'Director1': director1,
            'Director2': director2,
            'Duration': duration,
            'Year': year,
            'Ratings': ratings,
            'Metascore': metascore
        })

print("First CSV file created successfully.")

Requirement already satisfied: beautifulsoup4 in c:\users\ritul pawar\anaconda3\lib\site-packages (4.11.1)
Requirement already satisfied: requests in c:\users\ritul pawar\anaconda3\lib\site-packages (2.27.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\ritul pawar\anaconda3\lib\site-packages (from beautifulsoup4) (2.3.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ritul pawar\anaconda3\lib\site-packages (from requests) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\ritul pawar\anaconda3\lib\site-packages (from requests) (1.26.9)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ritul pawar\anaconda3\lib\site-packages (from requests) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\ritul pawar\anaconda3\lib\site-packages (from requests) (2.0.4)
First CSV file created successfully.

In [33]:
import pandas as pd

# Load the first CSV file into a DataFrame
df = pd.read_csv('movies_data.csv')

# Display the DataFrame
print(df)
df.columns

    Sno                                         Movie Name  \
0     1                                    The Dark Knight
1     2      The Lord of the Rings: The Return of the King
2     3                Spider-Man: Across the Spider-Verse
3     4                                          Inception
4     5  The Lord of the Rings: The Fellowship of the Ring
5     6              The Lord of the Rings: The Two Towers
6     7                                         The Matrix
7     8     Star Wars: Episode V - The Empire Strikes Back
8     9                                    Soorarai Pottru
9    10                         Terminator 2: Judgment Day
10   11                                          Star Wars
11   12                               Shichinin no samurai
12   13                                            Seppuku
13   14                                         Sita Ramam
14   15                                          Gladiator
15   16                                               Léon
16   17                            Raiders of the Lost Ark
17   18                  Spider-Man: Into the Spider-Verse
18   19                                             Aliens
19   20                                  Avengers: Endgame
20   21                                           Oldeuboi
21   22                              The Dark Knight Rises
22   23                             Avengers: Infinity War
23   24                                             Kaithi
24   25                                             Asuran
25   26                                  Top Gun: Maverick
26   27                                               Heat
27   28         Star Wars: Episode VI - Return of the Jedi
28   29                                      Mononoke-hime
29   30                                 North by Northwest
30   31                                             Dangal
31   32                                            Kantara
32   33                                   K.G.F: Chapter 2
33   34                                             Vikram
34   35                                          Shershaah
35   36                                           Ratsasan
36   37      Mission: Impossible - Dead Reckoning Part One
37   38                 Indiana Jones and the Last Crusade
38   39                            Spider-Man: No Way Home
39   40                                      Jurassic Park
40   41                                      Batman Begins
41   42                                               1917
42   43                                           Die Hard
43   44                                  Kill Bill: Vol. 1
44   45                                     V for Vendetta
45   46                 Kimetsu no Yaiba: Mugen Ressha-Hen
46   47                                                Ran
47   48                        Baahubali 2: The Conclusion
48   49                                 Gangs of Wasseypur
49   50                                            Yôjinbô

                Director1              Director2  Duration  Year  Ratings  \
0       Christopher Nolan         Christian Bale       152  2008      9.0
1           Peter Jackson            Elijah Wood       201  2003      9.0
2      Joaquim Dos Santos            Kemp Powers       140  2023      8.9
3       Christopher Nolan      Leonardo DiCaprio       148  2010      8.8
4           Peter Jackson            Elijah Wood       178  2001      8.8
5           Peter Jackson            Elijah Wood       179  2002      8.8
6          Lana Wachowski        Lilly Wachowski       136  1999      8.7
7          Irvin Kershner            Mark Hamill       124  1980      8.7
8           Sudha Kongara                 Suriya       153  2020      8.7
9           James Cameron  Arnold Schwarzenegger       137  1991      8.6
10           George Lucas            Mark Hamill       121  1977      8.6
11         Akira Kurosawa         Toshirô Mifune       207  1954      8.6
12       Masaki Kobayashi        Tatsuya Nakadai       133  1962      8.6
13       Hanu Raghavapudi        Dulquer Salmaan       163  2022      8.6
14           Ridley Scott          Russell Crowe       155  2000      8.5
15             Luc Besson              Jean Reno       110  1994      8.5
16       Steven Spielberg          Harrison Ford       115  1981      8.4
17        Bob Persichetti           Peter Ramsey       117  2018      8.4
18          James Cameron       Sigourney Weaver       137  1986      8.4
19          Anthony Russo              Joe Russo       181  2019      8.4
20         Park Chan-wook           Choi Min-sik       101  2003      8.4
21      Christopher Nolan         Christian Bale       164  2012      8.4
22          Anthony Russo              Joe Russo       149  2018      8.4
23       Lokesh Kanagaraj                 Karthi       145  2019      8.4
24            Vetrimaaran                Dhanush       141  2019      8.4
25        Joseph Kosinski             Tom Cruise       130  2022      8.3
26           Michael Mann              Al Pacino       170  1995      8.3
27       Richard Marquand            Mark Hamill       131  1983      8.3
28         Hayao Miyazaki           Yôji Matsuda       134  1997      8.3
29       Alfred Hitchcock             Cary Grant       136  1959      8.3
30          Nitesh Tiwari             Aamir Khan       161  2016      8.3
31          Rishab Shetty          Rishab Shetty       148  2022      8.3
32         Prashanth Neel                   Yash       168  2022      8.3
33       Lokesh Kanagaraj           Kamal Haasan       175  2022      8.3
34          Vishnuvardhan      Sidharth Malhotra       135  2021      8.3
35              Ram Kumar          Vishnu Vishal       170  2018      8.3
36  Christopher McQuarrie             Tom Cruise       163  2023      8.2
37       Steven Spielberg          Harrison Ford       127  1989      8.2
38              Jon Watts            Tom Holland       148  2021      8.2
39       Steven Spielberg              Sam Neill       127  1993      8.2
40      Christopher Nolan         Christian Bale       140  2005      8.2
41             Sam Mendes   Dean-Charles Chapman       119  2019      8.2
42         John McTiernan           Bruce Willis       132  1988      8.2
43      Quentin Tarantino            Uma Thurman       111  2003      8.2
44         James McTeigue           Hugo Weaving       132  2005      8.2
45         Haruo Sotozaki          Natsuki Hanae       117  2020      8.2
46         Akira Kurosawa        Tatsuya Nakadai       162  1985      8.2
47         S.S. Rajamouli                Prabhas       167  2017      8.2
48         Anurag Kashyap         Manoj Bajpayee       321  2012      8.2
49         Akira Kurosawa         Toshirô Mifune       110  1961      8.2

    Metascore
0        84.0
1        94.0
2        86.0
3        74.0
4        92.0
5        87.0
6        73.0
7        82.0
8         NaN
9        75.0
10       90.0
11       98.0
12       85.0
13        NaN
14       67.0
15       64.0
16       85.0
17       87.0
18       84.0
19       78.0
20       77.0
21       78.0
22       68.0
23        NaN
24        NaN
25       78.0
26       76.0
27       58.0
28       76.0
29       98.0
30        NaN
31        NaN
32        NaN
33        NaN
34        NaN
35        NaN
36       81.0
37       65.0
38       71.0
39       68.0
40       70.0
41       78.0
42       72.0
43       69.0
44       62.0
45       72.0
46       97.0
47        NaN
48       89.0
49       93.0

Index(['Sno', 'Movie Name', 'Director1', 'Director2', 'Duration', 'Year',
       'Ratings', 'Metascore'],
      dtype='object')

In [10]:
second_csv_file = 'movies_data_2.csv'
# Define the field names for the second CSV file
fieldnames = ['Movie Name', 'Star1', 'Star2', 'Star3', 'Star4', 'Votes', 'Genre1', 'Genre2', 'Genre3', 'Gross Collection', 'Popularity', 'Certification']

# Create and open the second CSV file in write mode
with open(second_csv_file, 'w', newline='', encoding='utf-8') as file:
    writer = csv.DictWriter(file, fieldnames=fieldnames)

    # Write the header row
    writer.writeheader()

    # Iterate over each movie
    for movie in movies:
        # Extract movie details
        title = movie.h3.a.text
        stars = movie.find('p', class_='').find_all('a')[0:4]
        star1 = stars[0].text if len(stars) > 0 else ""
        star2 = stars[1].text if len(stars) > 1 else ""
        star3 = stars[2].text if len(stars) > 2 else ""
        star4 = stars[3].text if len(stars) > 3 else ""
        votes = movie.find('span', attrs={'name': 'nv'})['data-value']
        genres = movie.find('span', class_='genre').text.strip().split(', ')
        genre1 = genres[0] if len(genres) > 0 else ""
        genre2 = genres[1] if len(genres) > 1 else ""
        genre3 = genres[2] if len(genres) > 2 else ""
        gross_collection = movie.find('span', attrs={'name': 'nv'})['data-value'] if movie.find('span', attrs={'name': 'nv'}) else ""
        popularity = movie.find('span', class_='text-muted').find_all('span')[-1].text.strip() if movie.find('span', class_='text-muted').find_all('span') else ""
        certification = movie.find('span', class_='certificate').text.strip() if movie.find('span', class_='certificate') else ""

        # Write movie data to the CSV file
        writer.writerow({
            'Movie Name': title,
            'Star1': star1,
            'Star2': star2,
            'Star3': star3,
            'Star4': star4,
            'Votes': votes,
            'Genre1': genre1,
            'Genre2': genre2,
            'Genre3': genre3,
            'Gross Collection': gross_collection,
            'Popularity': popularity,
            'Certification': certification
        })

print("Second CSV file created successfully.")

Second CSV file created successfully.

In [32]:
import pandas as pd

# Load the first CSV file into a DataFrame
df = pd.read_csv('movies_data_2.csv')

# Display the DataFrame
print(df)
df.columns

                                           Movie Name                  Star1  \
0                                     The Dark Knight      Christopher Nolan
1       The Lord of the Rings: The Return of the King          Peter Jackson
2                 Spider-Man: Across the Spider-Verse     Joaquim Dos Santos
3                                           Inception      Christopher Nolan
4   The Lord of the Rings: The Fellowship of the Ring          Peter Jackson
5               The Lord of the Rings: The Two Towers          Peter Jackson
6                                          The Matrix         Lana Wachowski
7      Star Wars: Episode V - The Empire Strikes Back         Irvin Kershner
8                                     Soorarai Pottru          Sudha Kongara
9                          Terminator 2: Judgment Day          James Cameron
10                                          Star Wars           George Lucas
11                               Shichinin no samurai         Akira Kurosawa
12                                            Seppuku       Masaki Kobayashi
13                                         Sita Ramam       Hanu Raghavapudi
14                                          Gladiator           Ridley Scott
15                                               Léon             Luc Besson
16                            Raiders of the Lost Ark       Steven Spielberg
17                  Spider-Man: Into the Spider-Verse        Bob Persichetti
18                                             Aliens          James Cameron
19                                  Avengers: Endgame          Anthony Russo
20                                           Oldeuboi         Park Chan-wook
21                              The Dark Knight Rises      Christopher Nolan
22                             Avengers: Infinity War          Anthony Russo
23                                             Kaithi       Lokesh Kanagaraj
24                                             Asuran            Vetrimaaran
25                                  Top Gun: Maverick        Joseph Kosinski
26                                               Heat           Michael Mann
27         Star Wars: Episode VI - Return of the Jedi       Richard Marquand
28                                      Mononoke-hime         Hayao Miyazaki
29                                 North by Northwest       Alfred Hitchcock
30                                             Dangal          Nitesh Tiwari
31                                            Kantara          Rishab Shetty
32                                   K.G.F: Chapter 2         Prashanth Neel
33                                             Vikram       Lokesh Kanagaraj
34                                          Shershaah          Vishnuvardhan
35                                           Ratsasan              Ram Kumar
36      Mission: Impossible - Dead Reckoning Part One  Christopher McQuarrie
37                 Indiana Jones and the Last Crusade       Steven Spielberg
38                            Spider-Man: No Way Home              Jon Watts
39                                      Jurassic Park       Steven Spielberg
40                                      Batman Begins      Christopher Nolan
41                                               1917             Sam Mendes
42                                           Die Hard         John McTiernan
43                                  Kill Bill: Vol. 1      Quentin Tarantino
44                                     V for Vendetta         James McTeigue
45                 Kimetsu no Yaiba: Mugen Ressha-Hen         Haruo Sotozaki
46                                                Ran         Akira Kurosawa
47                        Baahubali 2: The Conclusion         S.S. Rajamouli
48                                 Gangs of Wasseypur         Anurag Kashyap
49                                            Yôjinbô         Akira Kurosawa

                    Star2                 Star3                 Star4  \
0          Christian Bale          Heath Ledger         Aaron Eckhart
1             Elijah Wood       Viggo Mortensen          Ian McKellen
2             Kemp Powers    Justin K. Thompson         Shameik Moore
3       Leonardo DiCaprio  Joseph Gordon-Levitt           Elliot Page
4             Elijah Wood          Ian McKellen         Orlando Bloom
5             Elijah Wood          Ian McKellen       Viggo Mortensen
6         Lilly Wachowski          Keanu Reeves    Laurence Fishburne
7             Mark Hamill         Harrison Ford         Carrie Fisher
8                  Suriya          Paresh Rawal     Aparna Balamurali
9   Arnold Schwarzenegger        Linda Hamilton        Edward Furlong
10            Mark Hamill         Harrison Ford         Carrie Fisher
11         Toshirô Mifune       Takashi Shimura        Keiko Tsushima
12        Tatsuya Nakadai        Akira Ishihama        Shima Iwashita
13        Dulquer Salmaan         Mrunal Thakur     Rashmika Mandanna
14          Russell Crowe       Joaquin Phoenix        Connie Nielsen
15              Jean Reno           Gary Oldman       Natalie Portman
16          Harrison Ford           Karen Allen          Paul Freeman
17           Peter Ramsey        Rodney Rothman         Shameik Moore
18       Sigourney Weaver         Michael Biehn           Carrie Henn
19              Joe Russo     Robert Downey Jr.           Chris Evans
20           Choi Min-sik            Yoo Ji-tae        Kang Hye-jeong
21         Christian Bale             Tom Hardy         Anne Hathaway
22              Joe Russo     Robert Downey Jr.       Chris Hemsworth
23                 Karthi                Narain             Arjun Das
24                Dhanush         Manju Warrier           Prakash Raj
25             Tom Cruise     Jennifer Connelly          Miles Teller
26              Al Pacino        Robert De Niro            Val Kilmer
27            Mark Hamill         Harrison Ford         Carrie Fisher
28           Yôji Matsuda         Yuriko Ishida           Yûko Tanaka
29             Cary Grant       Eva Marie Saint           James Mason
30             Aamir Khan         Sakshi Tanwar    Fatima Sana Shaikh
31          Rishab Shetty      Kishore Kumar G.         Achyuth Kumar
32                   Yash           Sanjay Dutt        Raveena Tandon
33           Kamal Haasan      Vijay Sethupathi         Fahadh Faasil
34      Sidharth Malhotra          Kiara Advani          Shiv Panditt
35          Vishnu Vishal            Amala Paul            Radha Ravi
36             Tom Cruise         Hayley Atwell           Ving Rhames
37          Harrison Ford          Sean Connery          Alison Doody
38            Tom Holland               Zendaya  Benedict Cumberbatch
39              Sam Neill            Laura Dern         Jeff Goldblum
40         Christian Bale         Michael Caine          Ken Watanabe
41   Dean-Charles Chapman         George MacKay           Daniel Mays
42           Bruce Willis          Alan Rickman        Bonnie Bedelia
43            Uma Thurman       David Carradine          Daryl Hannah
44           Hugo Weaving       Natalie Portman         Rupert Graves
45          Natsuki Hanae            Akari Kitô   Yoshitsugu Matsuoka
46        Tatsuya Nakadai           Akira Terao         Jinpachi Nezu
47                Prabhas        Rana Daggubati        Anushka Shetty
48         Manoj Bajpayee   Nawazuddin Siddiqui      Tigmanshu Dhulia
49         Toshirô Mifune           Eijirô Tôno       Tatsuya Nakadai

      Votes     Genre1     Genre2     Genre3  Gross Collection  Popularity  \
0   2737930     Action      Crime      Drama           2737930         NaN
1   1897456     Action  Adventure      Drama           1897456         NaN
2    179975  Animation     Action  Adventure            179975         NaN
3   2429596     Action  Adventure     Sci-Fi           2429596         NaN
4   1925886     Action  Adventure      Drama           1925886         NaN
5   1712386     Action  Adventure      Drama           1712386         NaN
6   1969511     Action     Sci-Fi        NaN           1969511         NaN
7   1328745     Action  Adventure    Fantasy           1328745         NaN
8    119962     Action      Drama        NaN            119962         NaN
9   1130058     Action     Sci-Fi        NaN           1130058         NaN
10  1400947     Action  Adventure    Fantasy           1400947         NaN
11   354664     Action      Drama        NaN            354664         NaN
12    61954     Action      Drama    Mystery             61954         NaN
13    61289     Action      Drama    Mystery             61289         NaN
14  1544827     Action  Adventure      Drama           1544827         NaN
15  1196336     Action      Crime      Drama           1196336         NaN
16  1001437     Action  Adventure        NaN           1001437         NaN
17   606646  Animation     Action  Adventure            606646         NaN
18   736393     Action  Adventure     Sci-Fi            736393         NaN
19  1192877     Action  Adventure      Drama           1192877         NaN
20   600751     Action      Drama    Mystery            600751         NaN
21  1752444     Action      Drama   Thriller           1752444         NaN
22  1135369     Action  Adventure     Sci-Fi           1135369         NaN
23    36706     Action  Adventure      Crime             36706         NaN
24    31492     Action      Drama        NaN             31492         NaN
25   606931     Action      Drama        NaN            606931         NaN
26   682258     Action      Crime      Drama            682258         NaN
27  1083420     Action  Adventure    Fantasy           1083420         NaN
28   409873  Animation     Action  Adventure            409873         NaN
29   336151     Action  Adventure    Mystery            336151         NaN
30   198834     Action  Biography      Drama            198834         NaN
31    96692     Action  Adventure      Drama             96692         NaN
32   140771     Action      Crime      Drama            140771         NaN
33    64670     Action      Crime   Thriller             64670         NaN
34   125421     Action  Biography      Drama            125421         NaN
35    47410     Action      Crime      Drama             47410         NaN
36    25283     Action  Adventure   Thriller             25283         NaN
37   782196     Action  Adventure        NaN            782196         NaN
38   811801     Action  Adventure    Fantasy            811801         NaN
39  1021818     Action  Adventure     Sci-Fi           1021818         NaN
40  1512852     Action      Crime      Drama           1512852         NaN
41   628119     Action      Drama        War            628119         NaN
42   905503     Action   Thriller        NaN            905503         NaN
43  1146772     Action      Crime   Thriller           1146772         NaN
44  1145261     Action      Drama     Sci-Fi           1145261         NaN
45    65928  Animation     Action  Adventure             65928         NaN
46   130146     Action      Drama        War            130146         NaN
47   107962     Action      Drama        NaN            107962         NaN
48    99821     Action     Comedy      Crime             99821         NaN
49   126607     Action      Drama   Thriller            126607         NaN

   Certification
0             UA
1              U
2              U
3             UA
4              U
5             UA
6              A
7             UA
8              U
9              A
10             U
11             U
12           NaN
13             U
14            UA
15             A
16             A
17             U
18             U
19            UA
20             A
21            UA
22            UA
23            UA
24            UA
25            UA
26             A
27             U
28             U
29             U
30             U
31            UA
32            UA
33            UA
34            UA
35            UA
36            UA
37             U
38            UA
39            UA
40            UA
41             R
42             A
43             A
44            UA
45            UA
46     Not Rated
47            UA
48             A
49             U

Index(['Movie Name', 'Star1', 'Star2', 'Star3', 'Star4', 'Votes', 'Genre1',
       'Genre2', 'Genre3', 'Gross Collection', 'Popularity', 'Certification'],
      dtype='object')

# PHASE 2

In [23]:
import sqlite3

# Create SQLite database and establish connection
conn = sqlite3.connect('movies.db')
cursor = conn.cursor()

# Queries in Python

# 1) Display all the details of movies created by directors Christopher and Matt Reeves.
query1 = '''SELECT * FROM Table1
            WHERE Director1 IN ('Christopher Nolan', 'Matt Reeves')
               OR Director2 IN ('Christopher Nolan', 'Matt Reeves')'''
result1 = pd.read_sql_query(query1, conn)
print("Query 1 Result:\n", result1)

# 2) Display all the details of movies with a duration of 140 minutes to 190 minutes.
query2 = '''SELECT * FROM Table1
            WHERE Duration BETWEEN '140 ' AND '190 ' '''
cursor.execute(query2)
result2 = cursor.fetchall()
print("Query 2 Result:")
for row in result2:
    print(row)

# 3) Display all details of movies with ratings above 7 in ascending order.
query3 = '''SELECT * FROM Table1
            WHERE Ratings > 7
            ORDER BY Ratings ASC'''
result3 = pd.read_sql_query(query3, conn)
print("Query 3 Result:\n", result3)

# 4) Display all movie names in descending order.
query4 = '''SELECT `Movie Name` FROM Table1
            ORDER BY `Movie Name` DESC'''
result4 = pd.read_sql_query(query4, conn)
print("Query 4 Result:\n", result4)

# 5) Display movie names that start with 'P' and have a rating greater than 7.
query5 = '''SELECT "Movie Name" FROM Table1
            WHERE "Movie Name" LIKE 'P%' AND ratings > 7'''
cursor.execute(query5)
result5 = cursor.fetchall()
print("Query 5 Result:")
for row in result5:
    print(row[0])  
    # Display only the movie name

conn.close()

Query 1 Result:
    Sno             Movie Name          Director1          Director2  Duration  \
0    1        The Dark Knight  Christopher Nolan     Christian Bale       152
1    4              Inception  Christopher Nolan  Leonardo DiCaprio       148
2   22  The Dark Knight Rises  Christopher Nolan     Christian Bale       164
3   41          Batman Begins  Christopher Nolan     Christian Bale       140

   Year  Ratings  Metascore
0  2008      9.0       84.0
1  2010      8.8       74.0
2  2012      8.4       78.0
3  2005      8.2       70.0
Query 2 Result:
(1, 'The Dark Knight', 'Christopher Nolan', 'Christian Bale', 152, 2008, 9.0, 84.0)
(3, 'Spider-Man: Across the Spider-Verse', 'Joaquim Dos Santos', 'Kemp Powers', 140, 2023, 8.9, 86.0)
(4, 'Inception', 'Christopher Nolan', 'Leonardo DiCaprio', 148, 2010, 8.8, 74.0)
(5, 'The Lord of the Rings: The Fellowship of the Ring', 'Peter Jackson', 'Elijah Wood', 178, 2001, 8.8, 92.0)
(6, 'The Lord of the Rings: The Two Towers', 'Peter Jackson', 'Elijah Wood', 179, 2002, 8.8, 87.0)
(9, 'Soorarai Pottru', 'Sudha Kongara', 'Suriya', 153, 2020, 8.7, None)
(14, 'Sita Ramam', 'Hanu Raghavapudi', 'Dulquer Salmaan', 163, 2022, 8.6, None)
(15, 'Gladiator', 'Ridley Scott', 'Russell Crowe', 155, 2000, 8.5, 67.0)
(20, 'Avengers: Endgame', 'Anthony Russo', 'Joe Russo', 181, 2019, 8.4, 78.0)
(22, 'The Dark Knight Rises', 'Christopher Nolan', 'Christian Bale', 164, 2012, 8.4, 78.0)
(23, 'Avengers: Infinity War', 'Anthony Russo', 'Joe Russo', 149, 2018, 8.4, 68.0)
(24, 'Kaithi', 'Lokesh Kanagaraj', 'Karthi', 145, 2019, 8.4, None)
(25, 'Asuran', 'Vetrimaaran', 'Dhanush', 141, 2019, 8.4, None)
(27, 'Heat', 'Michael Mann', 'Al Pacino', 170, 1995, 8.3, 76.0)
(31, 'Dangal', 'Nitesh Tiwari', 'Aamir Khan', 161, 2016, 8.3, None)
(32, 'Kantara', 'Rishab Shetty', 'Rishab Shetty', 148, 2022, 8.3, None)
(33, 'K.G.F: Chapter 2', 'Prashanth Neel', 'Yash', 168, 2022, 8.3, None)
(34, 'Vikram', 'Lokesh Kanagaraj', 'Kamal Haasan', 175, 2022, 8.3, None)
(36, 'Ratsasan', 'Ram Kumar', 'Vishnu Vishal', 170, 2018, 8.3, None)
(37, 'Mission: Impossible - Dead Reckoning Part One', 'Christopher McQuarrie', 'Tom Cruise', 163, 2023, 8.2, 81.0)
(39, 'Spider-Man: No Way Home', 'Jon Watts', 'Tom Holland', 148, 2021, 8.2, 71.0)
(41, 'Batman Begins', 'Christopher Nolan', 'Christian Bale', 140, 2005, 8.2, 70.0)
(47, 'Ran', 'Akira Kurosawa', 'Tatsuya Nakadai', 162, 1985, 8.2, 97.0)
(48, 'Baahubali 2: The Conclusion', 'S.S. Rajamouli', 'Prabhas', 167, 2017, 8.2, None)
Query 3 Result:
     Sno                                         Movie Name  \
0    37      Mission: Impossible - Dead Reckoning Part One
1    38                 Indiana Jones and the Last Crusade
2    39                            Spider-Man: No Way Home
3    40                                      Jurassic Park
4    41                                      Batman Begins
5    42                                               1917
6    43                                           Die Hard
7    44                                  Kill Bill: Vol. 1
8    45                                     V for Vendetta
9    46                 Kimetsu no Yaiba: Mugen Ressha-Hen
10   47                                                Ran
11   48                        Baahubali 2: The Conclusion
12   49                                 Gangs of Wasseypur
13   50                                            Yôjinbô
14   26                                  Top Gun: Maverick
15   27                                               Heat
16   28         Star Wars: Episode VI - Return of the Jedi
17   29                                      Mononoke-hime
18   30                                 North by Northwest
19   31                                             Dangal
20   32                                            Kantara
21   33                                   K.G.F: Chapter 2
22   34                                             Vikram
23   35                                          Shershaah
24   36                                           Ratsasan
25   17                            Raiders of the Lost Ark
26   18                  Spider-Man: Into the Spider-Verse
27   19                                             Aliens
28   20                                  Avengers: Endgame
29   21                                           Oldeuboi
30   22                              The Dark Knight Rises
31   23                             Avengers: Infinity War
32   24                                             Kaithi
33   25                                             Asuran
34   15                                          Gladiator
35   16                                               Léon
36   10                         Terminator 2: Judgment Day
37   11                                          Star Wars
38   12                               Shichinin no samurai
39   13                                            Seppuku
40   14                                         Sita Ramam
41    7                                         The Matrix
42    8     Star Wars: Episode V - The Empire Strikes Back
43    9                                    Soorarai Pottru
44    4                                          Inception
45    5  The Lord of the Rings: The Fellowship of the Ring
46    6              The Lord of the Rings: The Two Towers
47    3                Spider-Man: Across the Spider-Verse
48    1                                    The Dark Knight
49    2      The Lord of the Rings: The Return of the King

                Director1              Director2  Duration  Year  Ratings  \
0   Christopher McQuarrie             Tom Cruise       163  2023      8.2
1        Steven Spielberg          Harrison Ford       127  1989      8.2
2               Jon Watts            Tom Holland       148  2021      8.2
3        Steven Spielberg              Sam Neill       127  1993      8.2
4       Christopher Nolan         Christian Bale       140  2005      8.2
5              Sam Mendes   Dean-Charles Chapman       119  2019      8.2
6          John McTiernan           Bruce Willis       132  1988      8.2
7       Quentin Tarantino            Uma Thurman       111  2003      8.2
8          James McTeigue           Hugo Weaving       132  2005      8.2
9          Haruo Sotozaki          Natsuki Hanae       117  2020      8.2
10         Akira Kurosawa        Tatsuya Nakadai       162  1985      8.2
11         S.S. Rajamouli                Prabhas       167  2017      8.2
12         Anurag Kashyap         Manoj Bajpayee       321  2012      8.2
13         Akira Kurosawa         Toshirô Mifune       110  1961      8.2
14        Joseph Kosinski             Tom Cruise       130  2022      8.3
15           Michael Mann              Al Pacino       170  1995      8.3
16       Richard Marquand            Mark Hamill       131  1983      8.3
17         Hayao Miyazaki           Yôji Matsuda       134  1997      8.3
18       Alfred Hitchcock             Cary Grant       136  1959      8.3
19          Nitesh Tiwari             Aamir Khan       161  2016      8.3
20          Rishab Shetty          Rishab Shetty       148  2022      8.3
21         Prashanth Neel                   Yash       168  2022      8.3
22       Lokesh Kanagaraj           Kamal Haasan       175  2022      8.3
23          Vishnuvardhan      Sidharth Malhotra       135  2021      8.3
24              Ram Kumar          Vishnu Vishal       170  2018      8.3
25       Steven Spielberg          Harrison Ford       115  1981      8.4
26        Bob Persichetti           Peter Ramsey       117  2018      8.4
27          James Cameron       Sigourney Weaver       137  1986      8.4
28          Anthony Russo              Joe Russo       181  2019      8.4
29         Park Chan-wook           Choi Min-sik       101  2003      8.4
30      Christopher Nolan         Christian Bale       164  2012      8.4
31          Anthony Russo              Joe Russo       149  2018      8.4
32       Lokesh Kanagaraj                 Karthi       145  2019      8.4
33            Vetrimaaran                Dhanush       141  2019      8.4
34           Ridley Scott          Russell Crowe       155  2000      8.5
35             Luc Besson              Jean Reno       110  1994      8.5
36          James Cameron  Arnold Schwarzenegger       137  1991      8.6
37           George Lucas            Mark Hamill       121  1977      8.6
38         Akira Kurosawa         Toshirô Mifune       207  1954      8.6
39       Masaki Kobayashi        Tatsuya Nakadai       133  1962      8.6
40       Hanu Raghavapudi        Dulquer Salmaan       163  2022      8.6
41         Lana Wachowski        Lilly Wachowski       136  1999      8.7
42         Irvin Kershner            Mark Hamill       124  1980      8.7
43          Sudha Kongara                 Suriya       153  2020      8.7
44      Christopher Nolan      Leonardo DiCaprio       148  2010      8.8
45          Peter Jackson            Elijah Wood       178  2001      8.8
46          Peter Jackson            Elijah Wood       179  2002      8.8
47     Joaquim Dos Santos            Kemp Powers       140  2023      8.9
48      Christopher Nolan         Christian Bale       152  2008      9.0
49          Peter Jackson            Elijah Wood       201  2003      9.0

    Metascore
0        81.0
1        65.0
2        71.0
3        68.0
4        70.0
5        78.0
6        72.0
7        69.0
8        62.0
9        72.0
10       97.0
11        NaN
12       89.0
13       93.0
14       78.0
15       76.0
16       58.0
17       76.0
18       98.0
19        NaN
20        NaN
21        NaN
22        NaN
23        NaN
24        NaN
25       85.0
26       87.0
27       84.0
28       78.0
29       77.0
30       78.0
31       68.0
32        NaN
33        NaN
34       67.0
35       64.0
36       75.0
37       90.0
38       98.0
39       85.0
40        NaN
41       73.0
42       82.0
43        NaN
44       74.0
45       92.0
46       87.0
47       86.0
48       84.0
49       94.0
Query 4 Result:
                                            Movie Name
0                                             Yôjinbô
1                                              Vikram
2                                      V for Vendetta
3                                   Top Gun: Maverick
4                                          The Matrix
5               The Lord of the Rings: The Two Towers
6       The Lord of the Rings: The Return of the King
7   The Lord of the Rings: The Fellowship of the Ring
8                               The Dark Knight Rises
9                                     The Dark Knight
10                         Terminator 2: Judgment Day
11         Star Wars: Episode VI - Return of the Jedi
12     Star Wars: Episode V - The Empire Strikes Back
13                                          Star Wars
14                            Spider-Man: No Way Home
15                  Spider-Man: Into the Spider-Verse
16                Spider-Man: Across the Spider-Verse
17                                    Soorarai Pottru
18                                         Sita Ramam
19                               Shichinin no samurai
20                                          Shershaah
21                                            Seppuku
22                                           Ratsasan
23                                                Ran
24                            Raiders of the Lost Ark
25                                           Oldeuboi
26                                 North by Northwest
27                                      Mononoke-hime
28      Mission: Impossible - Dead Reckoning Part One
29                                               Léon
30                 Kimetsu no Yaiba: Mugen Ressha-Hen
31                                  Kill Bill: Vol. 1
32                                            Kantara
33                                             Kaithi
34                                   K.G.F: Chapter 2
35                                      Jurassic Park
36                 Indiana Jones and the Last Crusade
37                                          Inception
38                                               Heat
39                                          Gladiator
40                                 Gangs of Wasseypur
41                                           Die Hard
42                                             Dangal
43                                      Batman Begins
44                        Baahubali 2: The Conclusion
45                             Avengers: Infinity War
46                                  Avengers: Endgame
47                                             Asuran
48                                             Aliens
49                                               1917
Query 5 Result:

In [25]:
df.columns

Index(['Movie Name', 'Star1', 'Star2', 'Star3', 'Star4', 'Votes', 'Genre1',
       'Genre2', 'Genre3', 'Gross Collection', 'Popularity', 'Certification'],
      dtype='object')

In [26]:
import sqlite3

# Create SQLite database and establish connection
conn = sqlite3.connect('movies.db')
cursor = conn.cursor()

# Queries in Python

# 1) Display all movie names with star Arnold Schwarzenegger in ascending order.
query1 = '''SELECT "Movie Name" FROM Table2
            WHERE Star1 LIKE '%Arnold Schwarzenegger%'
               OR Star2 LIKE '%Arnold Schwarzenegger%'
               OR Star3 LIKE '%Arnold Schwarzenegger%'
               OR Star4 LIKE '%Arnold Schwarzenegger%'
            ORDER BY "Movie Name" ASC'''
cursor.execute(query1)
result1 = cursor.fetchall()
print("Query 1 Result:")
for row in result1:
    print(row[0])

# 2) Display all details of the movie with the highest number of votes.
query2 = '''SELECT * FROM Table2
            WHERE Votes = (SELECT MAX(Votes) FROM Table2)'''
cursor.execute(query2)
result2 = cursor.fetchall()
print("Query 2 Result:")
for row in result2:
    print(row)

# 3) Display movie names with gross collections in descending order.
query3 = '''SELECT "Movie Name" FROM Table2
            WHERE "Gross Collection" IS NOT NULL
            ORDER BY "Gross Collection" DESC'''
cursor.execute(query3)
result3 = cursor.fetchall()
print("Query 3 Result:")
for row in result3:
    print(row[0])

# 4) Display the gross collection of movies with the star Arnold.
query4 = '''SELECT "Movie Name", "Gross Collection" FROM Table2
            WHERE Star1 LIKE '%Arnold Schwarzenegger%'
               OR Star2 LIKE '%Arnold Schwarzenegger%'
               OR Star3 LIKE '%Arnold Schwarzenegger%'
               OR Star4 LIKE '%Arnold Schwarzenegger%' '''
cursor.execute(query4)
result4 = cursor.fetchall()
print("Query 4 Result:")
for row in result4:
    print(row)

# 5) Display all details of movies with comedy and action genres.
query5 = '''SELECT * FROM Table2
            WHERE Genre1 LIKE '%Comedy%' AND Genre2 LIKE '%Action%' '''
cursor.execute(query5)
result5 = cursor.fetchall()
print("Query 5 Result:")
for row in result5:
    print(row)

# Close the connection to the SQLite database
conn.close()

Query 1 Result:
Terminator 2: Judgment Day
Query 2 Result:
('The Dark Knight', 'Christopher Nolan', 'Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 2737930, 'Action', 'Crime', 'Drama', 2737930, None, 'UA')
Query 3 Result:
The Dark Knight
Inception
The Matrix
The Lord of the Rings: The Fellowship of the Ring
The Lord of the Rings: The Return of the King
The Dark Knight Rises
The Lord of the Rings: The Two Towers
Gladiator
Batman Begins
Star Wars
Star Wars: Episode V - The Empire Strikes Back
Léon
Avengers: Endgame
Kill Bill: Vol. 1
V for Vendetta
Avengers: Infinity War
Terminator 2: Judgment Day
Star Wars: Episode VI - Return of the Jedi
Jurassic Park
Raiders of the Lost Ark
Die Hard
Spider-Man: No Way Home
Indiana Jones and the Last Crusade
Aliens
Heat
1917
Top Gun: Maverick
Spider-Man: Into the Spider-Verse
Oldeuboi
Mononoke-hime
Shichinin no samurai
North by Northwest
Dangal
Spider-Man: Across the Spider-Verse
K.G.F: Chapter 2
Ran
Yôjinbô
Shershaah
Soorarai Pottru
Baahubali 2: The Conclusion
Gangs of Wasseypur
Kantara
Kimetsu no Yaiba: Mugen Ressha-Hen
Vikram
Seppuku
Sita Ramam
Ratsasan
Kaithi
Asuran
Mission: Impossible - Dead Reckoning Part One
Query 4 Result:
('Terminator 2: Judgment Day', 1130058)
Query 5 Result:

In [31]:
df.columns

Index(['Movie Name', 'Star1', 'Star2', 'Star3', 'Star4', 'Votes', 'Genre1',
       'Genre2', 'Genre3', 'Gross Collection', 'Popularity', 'Certification'],
      dtype='object')

In [36]:
import sqlite3

# Create SQLite database and establish connection
conn = sqlite3.connect('movies.db')
cursor = conn.cursor()

# Subqueries in Python

# 1) Display all details from both tables where movie names are the same.
subquery1 = '''SELECT *
               FROM Table1
               INNER JOIN Table2 ON Table1."Movie Name" = Table2."Movie Name"'''
cursor.execute(subquery1)
result1 = cursor.fetchall()
print("Subquery 1 Result:")
for row in result1:
    print(row)

# 2) Display all movie names, Director, ratings, and gross collection where the genre is action.
subquery2 = '''SELECT Table1."Movie Name", Table1."Director1", Table1.Ratings, Table2."Gross Collection"
               FROM Table1
               INNER JOIN Table2 ON Table1."Movie Name" = Table2."Movie Name"
               WHERE Table2.Genre1 = 'Action' OR Table2.Genre2 = 'Action' OR Table2.Genre3 = 'Action' '''
cursor.execute(subquery2)
result2 = cursor.fetchall()
print("Subquery 2 Result:")
for row in result2:
    print(row)

# 3) Display all details from both tables with the highest gross collection.
subquery3 = '''SELECT *
               FROM Table1
               INNER JOIN Table2 ON Table1."Movie Name" = Table2."Movie Name"
               WHERE Table2."Gross Collection" = (SELECT MAX("Gross Collection") FROM Table2)'''
cursor.execute(subquery3)
result3 = cursor.fetchall()
print("Subquery 3 Result:")
for row in result3:
    print(row)

# 4) Display all details from both tables with the highest ratings.
subquery4 = '''SELECT *
               FROM Table1
               INNER JOIN Table2 ON Table1."Movie Name" = Table2."Movie Name"
               WHERE Table1.Ratings = (SELECT MAX(Ratings) FROM Table1)'''
cursor.execute(subquery4)
result4 = cursor.fetchall()
print("Subquery 4 Result:")
for row in result4:
    print(row)

# 5) Display all details from both tables with the lowest gross collection and lowest ratings.
subquery5 = '''SELECT *
               FROM Table1
               INNER JOIN Table2 ON Table1."Movie Name" = Table2."Movie Name"
               WHERE Table2."Gross Collection" = (SELECT MIN("Gross Collection") FROM Table2)
                   AND Table1.Ratings = (SELECT MIN(Ratings) FROM Table1)'''
cursor.execute(subquery5)
result5 = cursor.fetchall()
print("Subquery 5 Result:")
for row in result5:
    print(row)

# Close the connection to the SQLite database
conn.close()

Subquery 1 Result:
(1, 'The Dark Knight', 'Christopher Nolan', 'Christian Bale', 152, 2008, 9.0, 84.0, 'The Dark Knight', 'Christopher Nolan', 'Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 2737930, 'Action', 'Crime', 'Drama', 2737930, None, 'UA')
(2, 'The Lord of the Rings: The Return of the King', 'Peter Jackson', 'Elijah Wood', 201, 2003, 9.0, 94.0, 'The Lord of the Rings: The Return of the King', 'Peter Jackson', 'Elijah Wood', 'Viggo Mortensen', 'Ian McKellen', 1897456, 'Action', 'Adventure', 'Drama', 1897456, None, 'U')
(3, 'Spider-Man: Across the Spider-Verse', 'Joaquim Dos Santos', 'Kemp Powers', 140, 2023, 8.9, 86.0, 'Spider-Man: Across the Spider-Verse', 'Joaquim Dos Santos', 'Kemp Powers', 'Justin K. Thompson', 'Shameik Moore', 179975, 'Animation', 'Action', 'Adventure', 179975, None, 'U')
(4, 'Inception', 'Christopher Nolan', 'Leonardo DiCaprio', 148, 2010, 8.8, 74.0, 'Inception', 'Christopher Nolan', 'Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page', 2429596, 'Action', 'Adventure', 'Sci-Fi', 2429596, None, 'UA')
(5, 'The Lord of the Rings: The Fellowship of the Ring', 'Peter Jackson', 'Elijah Wood', 178, 2001, 8.8, 92.0, 'The Lord of the Rings: The Fellowship of the Ring', 'Peter Jackson', 'Elijah Wood', 'Ian McKellen', 'Orlando Bloom', 1925886, 'Action', 'Adventure', 'Drama', 1925886, None, 'U')
(6, 'The Lord of the Rings: The Two Towers', 'Peter Jackson', 'Elijah Wood', 179, 2002, 8.8, 87.0, 'The Lord of the Rings: The Two Towers', 'Peter Jackson', 'Elijah Wood', 'Ian McKellen', 'Viggo Mortensen', 1712386, 'Action', 'Adventure', 'Drama', 1712386, None, 'UA')
(7, 'The Matrix', 'Lana Wachowski', 'Lilly Wachowski', 136, 1999, 8.7, 73.0, 'The Matrix', 'Lana Wachowski', 'Lilly Wachowski', 'Keanu Reeves', 'Laurence Fishburne', 1969511, 'Action', 'Sci-Fi', None, 1969511, None, 'A')
(8, 'Star Wars: Episode V - The Empire Strikes Back', 'Irvin Kershner', 'Mark Hamill', 124, 1980, 8.7, 82.0, 'Star Wars: Episode V - The Empire Strikes Back', 'Irvin Kershner', 'Mark Hamill', 'Harrison Ford', 'Carrie Fisher', 1328745, 'Action', 'Adventure', 'Fantasy', 1328745, None, 'UA')
(9, 'Soorarai Pottru', 'Sudha Kongara', 'Suriya', 153, 2020, 8.7, None, 'Soorarai Pottru', 'Sudha Kongara', 'Suriya', 'Paresh Rawal', 'Aparna Balamurali', 119962, 'Action', 'Drama', None, 119962, None, 'U')
(10, 'Terminator 2: Judgment Day', 'James Cameron', 'Arnold Schwarzenegger', 137, 1991, 8.6, 75.0, 'Terminator 2: Judgment Day', 'James Cameron', 'Arnold Schwarzenegger', 'Linda Hamilton', 'Edward Furlong', 1130058, 'Action', 'Sci-Fi', None, 1130058, None, 'A')
(11, 'Star Wars', 'George Lucas', 'Mark Hamill', 121, 1977, 8.6, 90.0, 'Star Wars', 'George Lucas', 'Mark Hamill', 'Harrison Ford', 'Carrie Fisher', 1400947, 'Action', 'Adventure', 'Fantasy', 1400947, None, 'U')
(12, 'Shichinin no samurai', 'Akira Kurosawa', 'Toshirô Mifune', 207, 1954, 8.6, 98.0, 'Shichinin no samurai', 'Akira Kurosawa', 'Toshirô Mifune', 'Takashi Shimura', 'Keiko Tsushima', 354664, 'Action', 'Drama', None, 354664, None, 'U')
(13, 'Seppuku', 'Masaki Kobayashi', 'Tatsuya Nakadai', 133, 1962, 8.6, 85.0, 'Seppuku', 'Masaki Kobayashi', 'Tatsuya Nakadai', 'Akira Ishihama', 'Shima Iwashita', 61954, 'Action', 'Drama', 'Mystery', 61954, None, None)
(14, 'Sita Ramam', 'Hanu Raghavapudi', 'Dulquer Salmaan', 163, 2022, 8.6, None, 'Sita Ramam', 'Hanu Raghavapudi', 'Dulquer Salmaan', 'Mrunal Thakur', 'Rashmika Mandanna', 61289, 'Action', 'Drama', 'Mystery', 61289, None, 'U')
(15, 'Gladiator', 'Ridley Scott', 'Russell Crowe', 155, 2000, 8.5, 67.0, 'Gladiator', 'Ridley Scott', 'Russell Crowe', 'Joaquin Phoenix', 'Connie Nielsen', 1544827, 'Action', 'Adventure', 'Drama', 1544827, None, 'UA')
(16, 'Léon', 'Luc Besson', 'Jean Reno', 110, 1994, 8.5, 64.0, 'Léon', 'Luc Besson', 'Jean Reno', 'Gary Oldman', 'Natalie Portman', 1196336, 'Action', 'Crime', 'Drama', 1196336, None, 'A')
(17, 'Raiders of the Lost Ark', 'Steven Spielberg', 'Harrison Ford', 115, 1981, 8.4, 85.0, 'Raiders of the Lost Ark', 'Steven Spielberg', 'Harrison Ford', 'Karen Allen', 'Paul Freeman', 1001437, 'Action', 'Adventure', None, 1001437, None, 'A')
(18, 'Spider-Man: Into the Spider-Verse', 'Bob Persichetti', 'Peter Ramsey', 117, 2018, 8.4, 87.0, 'Spider-Man: Into the Spider-Verse', 'Bob Persichetti', 'Peter Ramsey', 'Rodney Rothman', 'Shameik Moore', 606646, 'Animation', 'Action', 'Adventure', 606646, None, 'U')
(19, 'Aliens', 'James Cameron', 'Sigourney Weaver', 137, 1986, 8.4, 84.0, 'Aliens', 'James Cameron', 'Sigourney Weaver', 'Michael Biehn', 'Carrie Henn', 736393, 'Action', 'Adventure', 'Sci-Fi', 736393, None, 'U')
(20, 'Avengers: Endgame', 'Anthony Russo', 'Joe Russo', 181, 2019, 8.4, 78.0, 'Avengers: Endgame', 'Anthony Russo', 'Joe Russo', 'Robert Downey Jr.', 'Chris Evans', 1192877, 'Action', 'Adventure', 'Drama', 1192877, None, 'UA')
(21, 'Oldeuboi', 'Park Chan-wook', 'Choi Min-sik', 101, 2003, 8.4, 77.0, 'Oldeuboi', 'Park Chan-wook', 'Choi Min-sik', 'Yoo Ji-tae', 'Kang Hye-jeong', 600751, 'Action', 'Drama', 'Mystery', 600751, None, 'A')
(22, 'The Dark Knight Rises', 'Christopher Nolan', 'Christian Bale', 164, 2012, 8.4, 78.0, 'The Dark Knight Rises', 'Christopher Nolan', 'Christian Bale', 'Tom Hardy', 'Anne Hathaway', 1752444, 'Action', 'Drama', 'Thriller', 1752444, None, 'UA')
(23, 'Avengers: Infinity War', 'Anthony Russo', 'Joe Russo', 149, 2018, 8.4, 68.0, 'Avengers: Infinity War', 'Anthony Russo', 'Joe Russo', 'Robert Downey Jr.', 'Chris Hemsworth', 1135369, 'Action', 'Adventure', 'Sci-Fi', 1135369, None, 'UA')
(24, 'Kaithi', 'Lokesh Kanagaraj', 'Karthi', 145, 2019, 8.4, None, 'Kaithi', 'Lokesh Kanagaraj', 'Karthi', 'Narain', 'Arjun Das', 36706, 'Action', 'Adventure', 'Crime', 36706, None, 'UA')
(25, 'Asuran', 'Vetrimaaran', 'Dhanush', 141, 2019, 8.4, None, 'Asuran', 'Vetrimaaran', 'Dhanush', 'Manju Warrier', 'Prakash Raj', 31492, 'Action', 'Drama', None, 31492, None, 'UA')
(26, 'Top Gun: Maverick', 'Joseph Kosinski', 'Tom Cruise', 130, 2022, 8.3, 78.0, 'Top Gun: Maverick', 'Joseph Kosinski', 'Tom Cruise', 'Jennifer Connelly', 'Miles Teller', 606931, 'Action', 'Drama', None, 606931, None, 'UA')
(27, 'Heat', 'Michael Mann', 'Al Pacino', 170, 1995, 8.3, 76.0, 'Heat', 'Michael Mann', 'Al Pacino', 'Robert De Niro', 'Val Kilmer', 682258, 'Action', 'Crime', 'Drama', 682258, None, 'A')
(28, 'Star Wars: Episode VI - Return of the Jedi', 'Richard Marquand', 'Mark Hamill', 131, 1983, 8.3, 58.0, 'Star Wars: Episode VI - Return of the Jedi', 'Richard Marquand', 'Mark Hamill', 'Harrison Ford', 'Carrie Fisher', 1083420, 'Action', 'Adventure', 'Fantasy', 1083420, None, 'U')
(29, 'Mononoke-hime', 'Hayao Miyazaki', 'Yôji Matsuda', 134, 1997, 8.3, 76.0, 'Mononoke-hime', 'Hayao Miyazaki', 'Yôji Matsuda', 'Yuriko Ishida', 'Yûko Tanaka', 409873, 'Animation', 'Action', 'Adventure', 409873, None, 'U')
(30, 'North by Northwest', 'Alfred Hitchcock', 'Cary Grant', 136, 1959, 8.3, 98.0, 'North by Northwest', 'Alfred Hitchcock', 'Cary Grant', 'Eva Marie Saint', 'James Mason', 336151, 'Action', 'Adventure', 'Mystery', 336151, None, 'U')
(31, 'Dangal', 'Nitesh Tiwari', 'Aamir Khan', 161, 2016, 8.3, None, 'Dangal', 'Nitesh Tiwari', 'Aamir Khan', 'Sakshi Tanwar', 'Fatima Sana Shaikh', 198834, 'Action', 'Biography', 'Drama', 198834, None, 'U')
(32, 'Kantara', 'Rishab Shetty', 'Rishab Shetty', 148, 2022, 8.3, None, 'Kantara', 'Rishab Shetty', 'Rishab Shetty', 'Kishore Kumar G.', 'Achyuth Kumar', 96692, 'Action', 'Adventure', 'Drama', 96692, None, 'UA')
(33, 'K.G.F: Chapter 2', 'Prashanth Neel', 'Yash', 168, 2022, 8.3, None, 'K.G.F: Chapter 2', 'Prashanth Neel', 'Yash', 'Sanjay Dutt', 'Raveena Tandon', 140771, 'Action', 'Crime', 'Drama', 140771, None, 'UA')
(34, 'Vikram', 'Lokesh Kanagaraj', 'Kamal Haasan', 175, 2022, 8.3, None, 'Vikram', 'Lokesh Kanagaraj', 'Kamal Haasan', 'Vijay Sethupathi', 'Fahadh Faasil', 64670, 'Action', 'Crime', 'Thriller', 64670, None, 'UA')
(35, 'Shershaah', 'Vishnuvardhan', 'Sidharth Malhotra', 135, 2021, 8.3, None, 'Shershaah', 'Vishnuvardhan', 'Sidharth Malhotra', 'Kiara Advani', 'Shiv Panditt', 125421, 'Action', 'Biography', 'Drama', 125421, None, 'UA')
(36, 'Ratsasan', 'Ram Kumar', 'Vishnu Vishal', 170, 2018, 8.3, None, 'Ratsasan', 'Ram Kumar', 'Vishnu Vishal', 'Amala Paul', 'Radha Ravi', 47410, 'Action', 'Crime', 'Drama', 47410, None, 'UA')
(37, 'Mission: Impossible - Dead Reckoning Part One', 'Christopher McQuarrie', 'Tom Cruise', 163, 2023, 8.2, 81.0, 'Mission: Impossible - Dead Reckoning Part One', 'Christopher McQuarrie', 'Tom Cruise', 'Hayley Atwell', 'Ving Rhames', 25283, 'Action', 'Adventure', 'Thriller', 25283, None, 'UA')
(38, 'Indiana Jones and the Last Crusade', 'Steven Spielberg', 'Harrison Ford', 127, 1989, 8.2, 65.0, 'Indiana Jones and the Last Crusade', 'Steven Spielberg', 'Harrison Ford', 'Sean Connery', 'Alison Doody', 782196, 'Action', 'Adventure', None, 782196, None, 'U')
(39, 'Spider-Man: No Way Home', 'Jon Watts', 'Tom Holland', 148, 2021, 8.2, 71.0, 'Spider-Man: No Way Home', 'Jon Watts', 'Tom Holland', 'Zendaya', 'Benedict Cumberbatch', 811801, 'Action', 'Adventure', 'Fantasy', 811801, None, 'UA')
(40, 'Jurassic Park', 'Steven Spielberg', 'Sam Neill', 127, 1993, 8.2, 68.0, 'Jurassic Park', 'Steven Spielberg', 'Sam Neill', 'Laura Dern', 'Jeff Goldblum', 1021818, 'Action', 'Adventure', 'Sci-Fi', 1021818, None, 'UA')
(41, 'Batman Begins', 'Christopher Nolan', 'Christian Bale', 140, 2005, 8.2, 70.0, 'Batman Begins', 'Christopher Nolan', 'Christian Bale', 'Michael Caine', 'Ken Watanabe', 1512852, 'Action', 'Crime', 'Drama', 1512852, None, 'UA')
(42, '1917', 'Sam Mendes', 'Dean-Charles Chapman', 119, 2019, 8.2, 78.0, '1917', 'Sam Mendes', 'Dean-Charles Chapman', 'George MacKay', 'Daniel Mays', 628119, 'Action', 'Drama', 'War', 628119, None, 'R')
(43, 'Die Hard', 'John McTiernan', 'Bruce Willis', 132, 1988, 8.2, 72.0, 'Die Hard', 'John McTiernan', 'Bruce Willis', 'Alan Rickman', 'Bonnie Bedelia', 905503, 'Action', 'Thriller', None, 905503, None, 'A')
(44, 'Kill Bill: Vol. 1', 'Quentin Tarantino', 'Uma Thurman', 111, 2003, 8.2, 69.0, 'Kill Bill: Vol. 1', 'Quentin Tarantino', 'Uma Thurman', 'David Carradine', 'Daryl Hannah', 1146772, 'Action', 'Crime', 'Thriller', 1146772, None, 'A')
(45, 'V for Vendetta', 'James McTeigue', 'Hugo Weaving', 132, 2005, 8.2, 62.0, 'V for Vendetta', 'James McTeigue', 'Hugo Weaving', 'Natalie Portman', 'Rupert Graves', 1145261, 'Action', 'Drama', 'Sci-Fi', 1145261, None, 'UA')
(46, 'Kimetsu no Yaiba: Mugen Ressha-Hen', 'Haruo Sotozaki', 'Natsuki Hanae', 117, 2020, 8.2, 72.0, 'Kimetsu no Yaiba: Mugen Ressha-Hen', 'Haruo Sotozaki', 'Natsuki Hanae', 'Akari Kitô', 'Yoshitsugu Matsuoka', 65928, 'Animation', 'Action', 'Adventure', 65928, None, 'UA')
(47, 'Ran', 'Akira Kurosawa', 'Tatsuya Nakadai', 162, 1985, 8.2, 97.0, 'Ran', 'Akira Kurosawa', 'Tatsuya Nakadai', 'Akira Terao', 'Jinpachi Nezu', 130146, 'Action', 'Drama', 'War', 130146, None, 'Not Rated')
(48, 'Baahubali 2: The Conclusion', 'S.S. Rajamouli', 'Prabhas', 167, 2017, 8.2, None, 'Baahubali 2: The Conclusion', 'S.S. Rajamouli', 'Prabhas', 'Rana Daggubati', 'Anushka Shetty', 107962, 'Action', 'Drama', None, 107962, None, 'UA')
(49, 'Gangs of Wasseypur', 'Anurag Kashyap', 'Manoj Bajpayee', 321, 2012, 8.2, 89.0, 'Gangs of Wasseypur', 'Anurag Kashyap', 'Manoj Bajpayee', 'Nawazuddin Siddiqui', 'Tigmanshu Dhulia', 99821, 'Action', 'Comedy', 'Crime', 99821, None, 'A')
(50, 'Yôjinbô', 'Akira Kurosawa', 'Toshirô Mifune', 110, 1961, 8.2, 93.0, 'Yôjinbô', 'Akira Kurosawa', 'Toshirô Mifune', 'Eijirô Tôno', 'Tatsuya Nakadai', 126607, 'Action', 'Drama', 'Thriller', 126607, None, 'U')
Subquery 2 Result:
('The Dark Knight', 'Christopher Nolan', 9.0, 2737930)
('The Lord of the Rings: The Return of the King', 'Peter Jackson', 9.0, 1897456)
('Spider-Man: Across the Spider-Verse', 'Joaquim Dos Santos', 8.9, 179975)
('Inception', 'Christopher Nolan', 8.8, 2429596)
('The Lord of the Rings: The Fellowship of the Ring', 'Peter Jackson', 8.8, 1925886)
('The Lord of the Rings: The Two Towers', 'Peter Jackson', 8.8, 1712386)
('The Matrix', 'Lana Wachowski', 8.7, 1969511)
('Star Wars: Episode V - The Empire Strikes Back', 'Irvin Kershner', 8.7, 1328745)
('Soorarai Pottru', 'Sudha Kongara', 8.7, 119962)
('Terminator 2: Judgment Day', 'James Cameron', 8.6, 1130058)
('Star Wars', 'George Lucas', 8.6, 1400947)
('Shichinin no samurai', 'Akira Kurosawa', 8.6, 354664)
('Seppuku', 'Masaki Kobayashi', 8.6, 61954)
('Sita Ramam', 'Hanu Raghavapudi', 8.6, 61289)
('Gladiator', 'Ridley Scott', 8.5, 1544827)
('Léon', 'Luc Besson', 8.5, 1196336)
('Raiders of the Lost Ark', 'Steven Spielberg', 8.4, 1001437)
('Spider-Man: Into the Spider-Verse', 'Bob Persichetti', 8.4, 606646)
('Aliens', 'James Cameron', 8.4, 736393)
('Avengers: Endgame', 'Anthony Russo', 8.4, 1192877)
('Oldeuboi', 'Park Chan-wook', 8.4, 600751)
('The Dark Knight Rises', 'Christopher Nolan', 8.4, 1752444)
('Avengers: Infinity War', 'Anthony Russo', 8.4, 1135369)
('Kaithi', 'Lokesh Kanagaraj', 8.4, 36706)
('Asuran', 'Vetrimaaran', 8.4, 31492)
('Top Gun: Maverick', 'Joseph Kosinski', 8.3, 606931)
('Heat', 'Michael Mann', 8.3, 682258)
('Star Wars: Episode VI - Return of the Jedi', 'Richard Marquand', 8.3, 1083420)
('Mononoke-hime', 'Hayao Miyazaki', 8.3, 409873)
('North by Northwest', 'Alfred Hitchcock', 8.3, 336151)
('Dangal', 'Nitesh Tiwari', 8.3, 198834)
('Kantara', 'Rishab Shetty', 8.3, 96692)
('K.G.F: Chapter 2', 'Prashanth Neel', 8.3, 140771)
('Vikram', 'Lokesh Kanagaraj', 8.3, 64670)
('Shershaah', 'Vishnuvardhan', 8.3, 125421)
('Ratsasan', 'Ram Kumar', 8.3, 47410)
('Mission: Impossible - Dead Reckoning Part One', 'Christopher McQuarrie', 8.2, 25283)
('Indiana Jones and the Last Crusade', 'Steven Spielberg', 8.2, 782196)
('Spider-Man: No Way Home', 'Jon Watts', 8.2, 811801)
('Jurassic Park', 'Steven Spielberg', 8.2, 1021818)
('Batman Begins', 'Christopher Nolan', 8.2, 1512852)
('1917', 'Sam Mendes', 8.2, 628119)
('Die Hard', 'John McTiernan', 8.2, 905503)
('Kill Bill: Vol. 1', 'Quentin Tarantino', 8.2, 1146772)
('V for Vendetta', 'James McTeigue', 8.2, 1145261)
('Kimetsu no Yaiba: Mugen Ressha-Hen', 'Haruo Sotozaki', 8.2, 65928)
('Ran', 'Akira Kurosawa', 8.2, 130146)
('Baahubali 2: The Conclusion', 'S.S. Rajamouli', 8.2, 107962)
('Gangs of Wasseypur', 'Anurag Kashyap', 8.2, 99821)
('Yôjinbô', 'Akira Kurosawa', 8.2, 126607)
Subquery 3 Result:
(1, 'The Dark Knight', 'Christopher Nolan', 'Christian Bale', 152, 2008, 9.0, 84.0, 'The Dark Knight', 'Christopher Nolan', 'Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 2737930, 'Action', 'Crime', 'Drama', 2737930, None, 'UA')
Subquery 4 Result:
(1, 'The Dark Knight', 'Christopher Nolan', 'Christian Bale', 152, 2008, 9.0, 84.0, 'The Dark Knight', 'Christopher Nolan', 'Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 2737930, 'Action', 'Crime', 'Drama', 2737930, None, 'UA')
(2, 'The Lord of the Rings: The Return of the King', 'Peter Jackson', 'Elijah Wood', 201, 2003, 9.0, 94.0, 'The Lord of the Rings: The Return of the King', 'Peter Jackson', 'Elijah Wood', 'Viggo Mortensen', 'Ian McKellen', 1897456, 'Action', 'Adventure', 'Drama', 1897456, None, 'U')
Subquery 5 Result:
(37, 'Mission: Impossible - Dead Reckoning Part One', 'Christopher McQuarrie', 'Tom Cruise', 163, 2023, 8.2, 81.0, 'Mission: Impossible - Dead Reckoning Part One', 'Christopher McQuarrie', 'Tom Cruise', 'Hayley Atwell', 'Ving Rhames', 25283, 'Action', 'Adventure', 'Thriller', 25283, None, 'UA')